# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ui-blue
#   labels: { app: ui, part-of: hospital-ml, tier: frontend, version: blue }
# spec:
#   replicas: 1
#   selector:
#     matchLabels: { app: ui, version: blue }
#   strategy:
#     type: RollingUpdate
#   template:
#     metadata:
#       labels: { app: ui, part-of: hospital-ml, tier: frontend, version: blue }
#     spec:
#       serviceAccountName: default
#       securityContext:
#         runAsUser: 1000
#         runAsGroup: 1000
#         fsGroup: 1000
#         fsGroupChangePolicy: Always
#       volumes:
#         - name: shared
#           persistentVolumeClaim: { claimName: shared-pvc }
#         - name: ui-config
#           configMap: { name: ui-config }
#       containers:
#         - name: ui
#           image: ui:1.2.7
#           imagePullPolicy: IfNotPresent
#           ports: [{ name: http, containerPort: 8501 }]
#           envFrom: [{ configMapRef: { name: ui-config } }]
#           volumeMounts:
#             - { name: shared, mountPath: /shared }
#             - { name: ui-config, mountPath: /app/.streamlit }
#           resources:
#             requests: { cpu: 100m, memory: 256Mi }
#             limits:   { cpu: 500m, memory: 512Mi }
#           readinessProbe: { tcpSocket: { port: http }, initialDelaySeconds: 5, periodSeconds: 10, timeoutSeconds: 2 }
#           livenessProbe:  { tcpSocket: { port: http }, initialDelaySeconds: 15, periodSeconds: 20, timeoutSeconds: 2 }
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-blue
  labels: { app: ui, part-of: hospital-ml, tier: frontend, version: blue }
spec:
  replicas: 1
  selector:
    matchLabels: { app: ui, version: blue }
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: { app: ui, part-of: hospital-ml, tier: frontend, version: blue }
    spec:
      serviceAccountName: default
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: Always
      volumes:
        - name: shared
          persistentVolumeClaim: { claimName: shared-pvc }
        - name: ui-config
          configMap: { name: ui-config }
      containers:
        - name: ui
          image: ui:1.2.7
          imagePullPolicy: IfNotPresent
          ports: [{ name: http, containerPort: 8501 }]
          envFrom: [{ configMapRef: { name: ui-config } }]
          volumeMounts:
            - { name: shared, mountPath: /shared }
            - { name: ui-config, mountPath: /app/.streamlit }
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 500m, memory: 512Mi }
          readinessProbe: { tcpSocket: { port: http }, initialDelaySeconds: 5, periodSeconds: 10, timeoutSeconds: 2 }
          livenessProbe:  { tcpSocket: { port: http }, initialDelaySeconds: 15, periodSeconds: 20, timeoutSeconds: 2 }