# -----------------------------------------------------------------------------
# PodDisruptionBudget for the ui pods.
# Ensures at least 1 pod is always available 
# during voluntary disruptions (e.g., upgrades, maintenance).
# -----------------------------------------------------------------------------

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ui-pdb
  namespace: hospital-ml
  labels:
    app: ui
    part-of: hospital-ml
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ui
