apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup-sa
  namespace: hospital-ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backup-role
  namespace: hospital-ml
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-rb
  namespace: hospital-ml
subjects:
  - kind: ServiceAccount
    name: backup-sa
    namespace: hospital-ml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backup-role
