apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: data-preprocessing-pdb
  namespace: hospital-ml
  labels:
    app: data-preprocessing
    part-of: hospital-ml
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: data-preprocessing
