apiVersion: v1
kind: ConfigMap
metadata:
  name: model-training-config
  namespace: hospital-ml
data:
  PREP_TARGET: "Target"
  PREP_SAVE_CSV: "true"
  PREP_LABEL_ENCODE_TARGET: "true"
  PREP_OUTPUT_DIR: "/shared/clean"               # <-- fixed
  MODEL_DIR: "/shared/models"                    # <-- fixed
  DEFAULT_DATASET_PATH: "/shared/data/diabetes_dataset00.csv"   # <-- fixed
---
apiVersion: v1
kind: Secret
metadata:
  name: model-training-secret
  namespace: hospital-ml
type: Opaque
stringData:
  TRAIN_AUTH_TOKEN: "change-me-before-demo"