apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: model-training-hpa
  namespace: hospital-ml
  labels:
    app: model-training
    part-of: hospital-ml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: model-training
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
