apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: model-training-pdb
  namespace: hospital-ml
  labels:
    app: model-training
    part-of: hospital-ml
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: model-training
