apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-preprocessing
  namespace: hospital-ml
  labels: { app: data-preprocessing }
spec:
  replicas: 1
  selector: { matchLabels: { app: data-preprocessing } }
  template:
    metadata: { labels: { app: data-preprocessing } }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001                   # ensure mounted volume is writable
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-shared
          image: busybox:1.36
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["sh","-c","mkdir -p /shared/data /shared/data/raw /shared/data/clean && chown -R 10001:10001 /shared"]
          volumeMounts:
            - name: shared
              mountPath: /shared
      containers:
      - name: data-preprocessing
        image: saikeerthan06/data-preprocessing:2.1.1
        imagePullPolicy: Always
        workingDir: /app
        env:
          - name: PYTHONPATH
            value: "/app"
          - name: PREP_OUTPUT_DIR
            value: "/shared/data/clean"      # <-- leading slash
          - name: PREP_TARGET
            value: "Target"
          - name: PREP_SAVE_CSV
            value: "true"
          - name: PREP_LABEL_ENCODE_TARGET
            value: "true"
        command: ["python"]
        args: ["-u", "data_preprocessing/service.py"]
        ports: [{ containerPort: 8000 }]
        volumeMounts:
          - name: shared
            mountPath: /shared           # <-- match your code path
        readinessProbe:
          httpGet: { path: /healthz, port: 8000 }
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 10
        livenessProbe:
          httpGet: { path: /healthz, port: 8000 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { cpu: "200m", memory: "256Mi" }
          limits:   { cpu: "1",    memory: "1Gi" }
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: shared-pvc        # <-- use the PVC you actually created
---
apiVersion: v1
kind: Service
metadata:
  name: data-preprocessing-svc
  namespace: hospital-ml
  labels: { app: data-preprocessing }
spec:
  selector: { app: data-preprocessing }
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
